[package]
name = "daoyi-cloud-logger"
version.workspace = true
edition.workspace = true

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
time = { workspace = true }