//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_oauth2_client")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub client_id: String,
    pub secret: String,
    pub name: String,
    pub logo: String,
    pub description: Option<String>,
    #[sea_orm(default_value = 0)]
    pub status: i8,
    pub access_token_validity_seconds: i32,
    pub refresh_token_validity_seconds: i32,
    pub redirect_uris: String,
    pub authorized_grant_types: String,
    pub scopes: Option<String>,
    pub auto_approve_scopes: Option<String>,
    pub authorities: Option<String>,
    pub resource_ids: Option<String>,
    pub additional_information: Option<String>,
    pub creator: Option<String>,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub create_time: DateTime,
    pub updater: Option<String>,
    #[sea_orm(on_update = "Expr::current_timestamp()")]
    pub update_time: DateTime,
    #[sea_orm(default_value = false)]
    pub deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
