//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_dict_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub sort: i32,
    pub label: String,
    pub value: String,
    pub dict_type: String,
    pub status: i8,
    pub color_type: Option<String>,
    pub css_class: Option<String>,
    pub remark: Option<String>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
