//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_sms_code")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub mobile: String,
    pub code: String,
    pub create_ip: String,
    pub scene: i8,
    pub today_index: i8,
    pub used: i8,
    pub used_time: Option<DateTime>,
    pub used_ip: Option<String>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
