//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_notify_message")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,
    pub user_type: i8,
    pub template_id: i64,
    pub template_code: String,
    pub template_nickname: String,
    pub template_content: String,
    pub template_type: i32,
    pub template_params: String,
    pub read_status: bool,
    pub read_time: Option<DateTime>,
    pub creator: Option<String>,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub create_time: DateTime,
    pub updater: Option<String>,
    #[sea_orm(on_update = "Expr::current_timestamp()")]
    pub update_time: DateTime,
    #[sea_orm(default_value = false)]
    pub deleted: bool,
    #[sea_orm(default_value = 0)]
    pub tenant_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
