//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_mail_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: Option<i64>,
    pub user_type: Option<i8>,
    pub to_mail: String,
    pub account_id: i64,
    pub from_mail: String,
    pub template_id: i64,
    pub template_code: String,
    pub template_nickname: Option<String>,
    pub template_title: String,
    pub template_content: String,
    pub template_params: String,
    pub send_status: i8,
    pub send_time: Option<DateTime>,
    pub send_message_id: Option<String>,
    pub send_exception: Option<String>,
    pub creator: Option<String>,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub create_time: DateTime,
    pub updater: Option<String>,
    #[sea_orm(on_update = "Expr::current_timestamp()")]
    pub update_time: DateTime,
    #[sea_orm(default_value = false)]
    pub deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
