//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_operate_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub trace_id: String,
    pub user_id: i64,
    pub user_type: i8,
    pub r#type: String,
    pub sub_type: String,
    pub biz_id: i64,
    pub action: String,
    pub extra: String,
    pub request_method: Option<String>,
    pub request_url: Option<String>,
    pub user_ip: Option<String>,
    pub user_agent: Option<String>,
    pub creator: Option<String>,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub create_time: DateTime,
    pub updater: Option<String>,
    #[sea_orm(on_update = "Expr::current_timestamp()")]
    pub update_time: DateTime,
    #[sea_orm(default_value = false)]
    pub deleted: bool,
    #[sea_orm(default_value = 0)]
    pub tenant_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
