[package]
name = "daoyi-cloud-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
[workspace]
resolver = "3"
members = [
    ".",
    "daoyi-cloud-*",
    "migration"
]
[workspace.package]
authors = ["Gemiman <gemiman@vip.qq.com>"]
edition = "2024"
homepage = "https://www.gemiman.com/"
license = "MIT"
publish = false
rust-version = "1.87.0"
version = "0.1.0"
repository = "https://github.com/daoyi-cloud-rust/daoyi-cloud-rust"
[workspace.dependencies]
anyhow = "1"
jsonwebtoken = "9"
salvo = "0"
serde = "1"
serde_json = "1"
thiserror = "2"
time = "0"
tokio = "1"
tracing = "0"
validator = "0"
ulid = "1"
argon2 = "0"
bcrypt = "0"
cookie = "0"
dotenvy = "0"
tracing-appender = "0"
tracing-subscriber = "0"
sea-orm = "1"
rand = "0.9"
toml = "0"
redis = "0"
wax = "0"
derive_more = "2"
chrono = "0"
reqwest = "0"
uuid = "1"
itertools = "0"
daoyi-cloud-app = { path = "daoyi-cloud-app", version = "0.1.0" }
daoyi-cloud-config = { path = "daoyi-cloud-config", version = "0.1.0" }
daoyi-cloud-entities = { path = "daoyi-cloud-entities", version = "0.1.0" }
daoyi-cloud-hoops = { path = "daoyi-cloud-hoops", version = "0.1.0" }
daoyi-cloud-models = { path = "daoyi-cloud-models", version = "0.1.0" }
daoyi-cloud-utils = { path = "daoyi-cloud-utils", version = "0.1.0" }
daoyi-cloud-service = { path = "daoyi-cloud-service", version = "0.1.0" }
