[package]
name = "daoyi-cloud-rs"
version.workspace = true
edition.workspace = true
[workspace]
members = [
    ".",
    "daoyi-cloud-api",
    "daoyi-cloud-common",
    "daoyi-cloud-core",
    "daoyi-cloud-middleware",
    "daoyi-cloud-system",
    "migration"
]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"

[dependencies]

[workspace.dependencies]
daoyi-cloud-api = { path = "daoyi-cloud-api" }
daoyi-cloud-common = { path = "daoyi-cloud-common" }
daoyi-cloud-core = { path = "daoyi-cloud-core" }
daoyi-cloud-middleware = { path = "daoyi-cloud-middleware" }
spring = "0"
spring-web = "0"
spring-sea-orm = "0"
tokio = "1"
anyhow = "1"
thiserror = "2"
sea-orm = "1"
serde = "1"
serde_json = "1"
