[package]
name = "daoyi-cloud-system"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
daoyi-cloud-logger = { workspace = true }
daoyi-cloud-config = { workspace = true }