//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use crate::entity::BaseEntityTrait;
use sea_orm::Set;
use sea_orm::entity::prelude::*;
use sea_orm::prelude::async_trait::async_trait;
use sea_orm::sqlx::types::chrono::Local;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_sms_code")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub mobile: String,
    pub code: String,
    pub create_ip: String,
    pub scene: i8,
    pub today_index: i8,
    pub used: i8,
    pub used_time: Option<DateTime>,
    pub used_ip: Option<String>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: i64,
}

impl BaseEntityTrait for ActiveModel {
    fn set_creator(&mut self, u: String) {
        self.creator = Set(Some(u));
    }

    fn set_updater(&mut self, u: String) {
        self.updater = Set(Some(u));
    }

    fn set_tenant_id(&mut self, t: i64) {
        self.tenant_id = Set(t);
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            self.create_time = Set(Local::now().naive_local());
        }
        self.update_time = Set(Local::now().naive_local());
        Ok(self)
    }
}
