//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use crate::entity::BaseEntityTrait;
use chrono::Local;
use sea_orm::Set;
use sea_orm::entity::prelude::*;
use sea_orm::prelude::async_trait::async_trait;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_tenant")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub contact_user_id: Option<i64>,
    pub contact_name: String,
    pub contact_mobile: Option<String>,
    pub status: i8,
    pub website: Option<String>,
    pub package_id: i64,
    pub expire_time: DateTime,
    pub account_count: i32,
    pub creator: String,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
}

impl BaseEntityTrait for ActiveModel {
    fn set_creator(&mut self, u: String) {
        self.creator = Set(u);
    }

    fn set_updater(&mut self, u: String) {
        self.updater = Set(Some(u));
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            self.create_time = Set(Local::now().naive_local());
        }
        self.update_time = Set(Local::now().naive_local());
        Ok(self)
    }
}
