//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::Set;
use sea_orm::entity::prelude::*;
use sea_orm::prelude::async_trait::async_trait;
use sea_orm::sqlx::types::chrono::Local;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_oauth2_client")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub client_id: String,
    pub secret: String,
    pub name: String,
    pub logo: String,
    pub description: Option<String>,
    pub status: i8,
    pub access_token_validity_seconds: i32,
    pub refresh_token_validity_seconds: i32,
    pub redirect_uris: String,
    pub authorized_grant_types: String,
    pub scopes: Option<String>,
    pub auto_approve_scopes: Option<String>,
    pub authorities: Option<String>,
    pub resource_ids: Option<String>,
    pub additional_information: Option<String>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            self.create_time = Set(Local::now().naive_local());
        }
        self.update_time = Set(Local::now().naive_local());
        Ok(self)
    }
}
